#!/bin/bash

if [ $(id -u) -ne 0 ]; then
  echo "We need root access to install the prerequisites. 
Please run this script again with Sudo."
  exit 1
fi


if test -e /etc/debian_version ; then
  apt-get install -y \
    libegl1-mesa-dev \
    libfontconfig1-dev \
    libx11-xcb-dev \
    libxcb-ewmh-dev \
    libxcb-icccm4-dev \
    libxcb-keysyms1-dev \
    libharfbuzz-dev \
    libxkbcommon-x11-dev \
    libfreetype6-dev
  exit $?
fi

if test -e /etc/arch-release ; then
  pacman -S --noconfirm --needed \
    'fontconfig' \
    'freetype2' \
    'libxkbcommon-x11' \
    'xcb-util-keysyms' \
    'xcb-util-wm'
  exit $?
fi

if test -e /etc/gentoo-release ; then
  emerge -j \
    'media-libs/fontconfig' \
    'media-libs/freetype' \
    'x11-libs/libxkbcommon' \
    'x11-libs/xcb-util'
  exit $?
fi

echo "No deps found for your system,"
echo "please contribute the commands to install the deps."
exit 1
